language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors
  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then pip install -r cpython_requirements.txt --use-mirrors; fi

script: python setup.py test

